version: "3.7"
services:
  frontend-stubrunner:
    image: springcloud/spring-cloud-contract-stub-runner:2.1.1.RELEASE
    ports:
      - 8083:8083
      - 9876:9876
    env_file:
      - .env
    environment:
      SC_CONTRACT_DOCKER_VERSION: 2.1.1.RELEASE
      STUBRUNNER_PORT: 8083
      STUBRUNNER_STUBS_MODE: REMOTE
#      STUBRUNNER_USERNAME: ${STUBRUNNER_USERNAME}
#      STUBRUNNER_PASSWORD: ${STUBRUNNER_PASSWORD}
#      STUBRUNNER_IDS: ${STUBRUNNER_STUBS_ARTIFACT}
#      STUBRUNNER_REPOSITORY_ROOT: ${STUBRUNNER_REPOSITORY_PATH}